### ISSUE TITLE
Missing data file for tests: kafka_011.log

### ISSUE THREAD

**Issue by guidog** [nash-io/jocko#6]
Looking at the failing tests it seems that a data file is missing.
The failing test is in directory jocko/protocol.

go test -v produces:
    TestRecordBatchDecodeKafka011: record_batch_test.go:14: open kafka_011.log: no such file or directory

Any chance to add the file?

**Comment by canesin** [comment]
I searched all the originals forks for that file and couldn't find yet. Since `*.log` is in the .gitignore since initial commit I believe it is lost.
One can probably nuke that test.

**Comment by guidog** [comment]
Ouch!
Will delete the whole 'report_batch_test.go' file then.

**Comment by snichme** [comment]
Here is the missing file, that test wasn't suppose to have a dependency against a file, my idea was to include the []byte of the content inside the test. 
The file is a copy of a log file generated by kafka 0.11.0.2 and was a good test targer. 

[kafka_011.log](https://github.com/nash-io/jocko/files/4345189/kafka_011.log)

**Comment by canesin** [comment]
Thanks @snichme! If you want :sweat_smile: to do it I just commented the test instead of removing it.
